version: 2

jobs:
  build:
    environment:
      IMAGE_NAME: pioka/spresensesdk-builder
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .

      - run:
          name: Test building helloworld
          command: >-
            docker run $IMAGE_NAME:latest
            bash -c 'git clone --recursive https://github.com/sonydevworld/spresense.git &&
            cd spresense/sdk &&
            ./tools/config.py --kernel release &&
            ./tools/config.py examples/hello &&
            make buildkernel &&
            make'

      - deploy:
          name: Publish Docker image to DockerHub
          command: |
            DATE=`date '+%Y%m%d'`
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$DATE

            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $IMAGE_NAME:$DATE
            docker push $IMAGE_NAME:latest
